AWSTemplateFormatVersion: 2010-09-09
Description: Ec2 block device mapping
Resources: 
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-009d6802948d06e52
      AvailabilityZone: us-east-1a
      KeyName: privateKey
      InstanceType: t2.micro



AWSTemplateFormatVersion: 2010-09-09
Description: ec2-stack
Resources:
  sampleec2:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-1a
      InstanceType: m1.small
      DisableApiTermination: true
      ImageId: ami-79fd7eee
      KeyName: privateKey